/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.tools.Tool;

/**
 *
 * @author AnyJM1
 */
public class fondo extends javax.swing.JFrame {

    /**
     * Creates new form fondo
     */
    public fondo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LOGO.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        valorTEM = new java.awt.TextField();
        valorP = new java.awt.TextField();
        valorN = new java.awt.TextField();
        textp = new javax.swing.JLabel();
        texttem = new javax.swing.JLabel();
        textn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipoexel = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        table = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondoazul = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Frances - Amortizaciones");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("Sistema Frances - Amortizaciones"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorTEM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numtem(evt);
            }
        });
        jPanel1.add(valorTEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 30));

        valorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPActionPerformed(evt);
            }
        });
        valorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nump(evt);
            }
        });
        jPanel1.add(valorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 140, 30));

        valorN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numn(evt);
            }
        });
        jPanel1.add(valorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 30));

        textp.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        textp.setForeground(new java.awt.Color(255, 255, 255));
        textp.setText("P: ");
        textp.setToolTipText("");
        jPanel1.add(textp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));
        textp.getAccessibleContext().setAccessibleName("");

        texttem.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        texttem.setForeground(new java.awt.Color(255, 255, 255));
        texttem.setText("TEM: ");
        texttem.setToolTipText("");
        jPanel1.add(texttem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        textn.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        textn.setForeground(new java.awt.Color(255, 255, 255));
        textn.setText("n: ");
        textn.setToolTipText("");
        jPanel1.add(textn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Periodos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inversion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tipoexel.setBackground(new java.awt.Color(0, 51, 102));
        tipoexel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla.setBackground(new java.awt.Color(204, 204, 255));
        tabla.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "n°", "MENSUALIDADES", "INTERES", "AMORTIZACION", "SALDO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(0, 0, 51));
        tipoexel.setViewportView(tabla);

        jPanel1.add(tipoexel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 610, 410));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("©AnyJM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        salir.setBackground(new java.awt.Color(0, 51, 102));
        salir.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        table.setBackground(new java.awt.Color(0, 51, 102));
        table.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setText("MOSTRAR TABLA");
        table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableActionPerformed(evt);
            }
        });
        jPanel1.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ejm: 0.5");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SISTEMA FRANCÉS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 130, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tasa efectiva mensual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        fondoazul.setForeground(new java.awt.Color(255, 255, 255));
        fondoazul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        fondoazul.setText("Tasa efectiva mensual");
        jPanel1.add(fondoazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 570));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ejm: 0.5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ejm: 0.5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ejm: 0.5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
      
        System.exit(0);
        
    }//GEN-LAST:event_salirActionPerformed

    private void tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableActionPerformed
        // SISTEMA FRANCES
               
              
        //si n es menor q las columnas dadas, resta las filas
        //si n es mayor q las columna dadas, agrega filas
        //filas,columnas
        if( valorN.getText().equals("") || valorP.getText().equals("") || valorTEM.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Ingrese valores faltantes", "Error, campos vacios", JOptionPane.ERROR_MESSAGE);
            System.out.println("error!!");
              
        }
        else
        {
            
           //sino realiza las operaciones 
           
        float p=Float.parseFloat(valorP.getText());
        int n= Integer.parseInt(valorN.getText());
        float tem=Float.parseFloat(valorTEM.getText()); 
        
        System.out.println("capital"+p);
        System.out.println("cuotas: "+n);
        System.out.println("tasa:"+tem);
        //fila , columna
       
        DefaultTableModel model = new DefaultTableModel(n+1, 5);  
                
        //editar nombre de columnas
        String[] nombrescol = {"n°", "MENSUALIDADES", "INTERES","AMORTIZACION","SALDO"};       
        model.setColumnIdentifiers(nombrescol);
        
        
        //muestra los valores de las cuaotas
        for(int i=0;i<n+1;i++)            
        {model.setValueAt(i,i,0);}
        
        //coloca saldo inicial
        model.setValueAt(p, 0, 4);
        
        //mensualidad
        double A=tem*Math.pow(1+tem,n);
        double B=Math.pow(1+tem,n)-1;
        double mensualidad=p*A/B;
        
      
        
            System.out.println("mensualidad:"+mensualidad);
            
            
            //mensualidades
             for(int i=1;i<n+1;i++)  
         {         //fila , columna    
            model.setValueAt(mensualidad,i,1);
         }
           
        int j=0;
        double saldo=0;
        double interes=0;
        double amortizacion=0;
        double ns=0;
         for(int i=1;i<n+1;i++)  
         {
             //intereses
                    //fila , columna             
             saldo= Double.parseDouble(model.getValueAt(j, 4).toString()); 
             interes=saldo*tem;
             
             
             model.setValueAt(interes,i,2);
                          
             //amortizaciones
                    //fila , columna    
            amortizacion=mensualidad-interes;
            
            
            model.setValueAt(amortizacion,i,3);            
            j++;            
            ns=saldo-amortizacion;            
           
            
            model.setValueAt(ns,i,4);            
            
         }
        if(Double.parseDouble(model.getValueAt(n,4).toString())<=0)
        { 
            System.out.println(model.getValueAt(n,4).toString());
            model.setValueAt(0, n,4);
        }
        
        tabla.setModel(model);
        }
        
    }//GEN-LAST:event_tableActionPerformed

    private void nump(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nump
        // TODO add your handling code here:
           
         char a= evt.getKeyChar();
         
    if ( Character.isLetter(a) ) 
    {
        valorP.setEditable(false);
        
    } 
    else 
    {
        valorP.setEditable(true);
        
    }
        
    }//GEN-LAST:event_nump

    private void numn(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numn
        // TODO add your handling code here:
              
         char a= evt.getKeyChar();
         
    if ( Character.isLetter(a) ) 
    {
        valorN.setEditable(false);
        
    } 
    else 
    {
        valorN.setEditable(true);
        
    }
        
    
        
    }//GEN-LAST:event_numn

    private void valorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPActionPerformed

    private void numtem(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numtem
        // TODO add your handling code here:
        
             char a= evt.getKeyChar();
         
    if ( Character.isLetter(a)  ) 
    {
        valorTEM.setEditable(false);
        
    } 
    else 
    {
        valorTEM.setEditable(true);
        
    }
    }//GEN-LAST:event_numtem

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fondo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoazul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JButton table;
    private javax.swing.JLabel textn;
    private javax.swing.JLabel textp;
    private javax.swing.JLabel texttem;
    private javax.swing.JScrollPane tipoexel;
    private java.awt.TextField valorN;
    private java.awt.TextField valorP;
    private java.awt.TextField valorTEM;
    // End of variables declaration//GEN-END:variables
}
